#+title: Readme

Based on [[https://github.com/rien/reStream][reStream]]

* Dependencies

You need

- Gstreamer
- Gstreamer Plugins Base
- Gstreamer Plugins Good

** Ubuntu

#+begin_src shell
sudo apt install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
#+end_src

** openSUSE

#+begin_src shell
sudo zypper install gstreamer gstreamer-plugins-base gstreamer-plugins-good
#+end_src

* Usage

** Server

The must be running.

To install it, first build (see later in this document) and then copy it to your reMarkable.

#+begin_src shell
scp review-server.arm.static root@${REMARKABLE_IP}:review-server
#+end_src

And then start it manually.

#+begin_src shell
ssh root@${REMARKABLE_IP} 'RUST_LOG=trace ./review-server --port 6680'
#+end_src

TODO: Install it as service

** Client

Options for the client can be set as command line options or environment variables.
Command line options override the environment variables.

Values with no default value in their description have to be set (for example =--ssh-key=).

*** Command Line Options

#+begin_src
Usage: review-client [OPTIONS]

Options:
      --remarkable-ip <remarkable-ip>  IP of the reMarkable tablet (default: 10.11.99.1)
      --tcp-port <tcp-port>            TCP port for video stream (default: 6680)
      --framerate <framerate>          Framerate (default: 50)
      --dark-mode                      Dark mode - invert colors (default: false)
      --show-cursor                    Show cursor (default: false)
  -h, --help                           Print help
  -V, --version                        Print version
#+end_src

*** Environment Variables

Corresponding keys:
- =REMARKABLE_IP=
- =REMARKABLE_TCP_PORT=
# - =REMARKABLE_SSH_KEY_PATH=
- =REMARKABLE_FRAMERATE=
- =REMARKABLE_DARK_MODE=
- =REMARKABLE_SHOW_CURSOR=

* Building

** Client

Just build it

#+begin_src shell
cargo build --release --bin review-client
#+end_src

Or with [[https://dagger.io/][dagger]]

#+begin_src shell
dagger call build-client --source . export --path review-client
#+end_src

** Server

With [[https://dagger.io/][dagger]]

#+begin_src shell
dagger call build-server --source . export --path review-server.arm.static
#+end_src

* Development

** Additional Dependencies

*** openSUSE

#+begin_src shell
sudo zypper in gstreamer-devel gstreamer-plugins-base-devel
#+end_src

